function error(erro) {
    throw `Ocorreu um Erro no Sistema!
    Por Favor Atualizar o Sistema...`
}

const teste = require('./arrayfuncao')
console.log(teste)

function op(a, b) {
    try {
        const v = a + x
    } catch(erro){
        error()
    }finally{
        console.log('-')
        console.log('--')
        console.log('---')
        console.log('--')
        console.log('-')
    }
}

let n1,n2
n1 = 5
n2 = 8
op(5,8)

